apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds
---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: terraform-provider
spec:
  credentials:
  - filename: aws-creds.ini
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: credentials
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: creds   
  configuration: |
    provider "aws" {
        shared_credentials_file = "aws-creds.ini"
        region                  = "us-east-1"
    }
    
    terraform {
      backend "s3" {
        bucket = "us-marcyoung-crossplane"
        key    = "terraform.tfstate"
        region = "us-east-1"
      }
    }
