apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: us-marcyoung-crossplane
  namespace: crossplane-system
spec:
  forProvider:
    acl: private
    locationConstraint: us-east-1
    objectLockEnabledForBucket: false
  providerConfigRef:
    name: aws-provider
